# Generated by Django 3.1.1 on 2020-09-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
