# Generated by Django 3.1.1 on 2020-09-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_instagram_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
    ]
