# Generated by Django 3.1.1 on 2020-09-29 16:16

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200927_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='profilepics/'),
        ),
    ]
